services:
  - type: web
    name: qu-quiz-app
    env: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm run seed && npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
